package ExceptionHandling;

public class User {

	public static void main(String[] args) {
//		System.out.println("A");
//		System.out.println("A");
//		System.out.println("A");
//		
//		try {
//			int i=9/3;
//			System.out.println("Hey nanba.. ");
//		} catch(ArithmeticException ae) {
//			ae.printStackTrace();
//		}
//		// finally will always be executed
//		// finally will be associated with catch block
//		finally { 
//			System.out.println("im in finally block");
//		}
		
		System.out.println("-------------");
		
//		try {
//			int p = 10/0; // throwing the exception 
//		}
//		finally {
//			System.out.println("in 2nd finally");
//		}
//		
//		System.out.println("Bye !");
		
		
		System.out.println("-------------");
//		Valid sequence ---- 
		
//		try
//		catch
//		finally
		
//		try
//		finally
		
//		Invalid sequence
//		catch
//		finally

	}

}
